export type TextEditorCompletionItem = {
  id: string;
  trigger: string;
  label: string;
  detail: string;
  snippet: string;
  keywords?: string[];
};

export const TEXT_NODE_SYMBOL_COMPLETIONS: TextEditorCompletionItem[] = [
  { id: "alpha", trigger: "\\alpha", label: "α", detail: "Greek alpha", snippet: "α", keywords: ["alpha"] },
  { id: "beta", trigger: "\\beta", label: "β", detail: "Greek beta", snippet: "β", keywords: ["beta"] },
  { id: "gamma", trigger: "\\gamma", label: "γ", detail: "Greek gamma", snippet: "γ", keywords: ["gamma"] },
  { id: "mathbb-n", trigger: "\\mathbb{N}", label: "ℕ", detail: "Natural numbers", snippet: "ℕ", keywords: ["naturals"] },
  { id: "mathbb-z", trigger: "\\mathbb{Z}", label: "ℤ", detail: "Integers", snippet: "ℤ", keywords: ["integers"] },
  { id: "mathbb-q", trigger: "\\mathbb{Q}", label: "ℚ", detail: "Rationals", snippet: "ℚ", keywords: ["rationals"] },
  { id: "mathbb-r", trigger: "\\mathbb{R}", label: "ℝ", detail: "Reals", snippet: "ℝ", keywords: ["reals"] },
  { id: "leq", trigger: "\\leq", label: "≤", detail: "Less than or equal", snippet: "≤" },
  { id: "geq", trigger: "\\geq", label: "≥", detail: "Greater than or equal", snippet: "≥" },
  { id: "neq", trigger: "\\neq", label: "≠", detail: "Not equal", snippet: "≠" },
  { id: "times", trigger: "\\times", label: "×", detail: "Times", snippet: "×" },
  { id: "cdot", trigger: "\\cdot", label: "·", detail: "Centered dot", snippet: "·" },
  { id: "pm", trigger: "\\pm", label: "±", detail: "Plus minus", snippet: "±" },
  { id: "to", trigger: "\\to", label: "→", detail: "Arrow", snippet: "→" },
  { id: "infty", trigger: "\\infty", label: "∞", detail: "Infinity", snippet: "∞" },
  { id: "subseteq", trigger: "\\subseteq", label: "⊆", detail: "Subset or equal", snippet: "⊆" },
  { id: "subset", trigger: "\\subset", label: "⊂", detail: "Subset", snippet: "⊂" },
  { id: "cup", trigger: "\\cup", label: "∪", detail: "Union", snippet: "∪" },
  { id: "cap", trigger: "\\cap", label: "∩", detail: "Intersection", snippet: "∩" },
];

export const DEFAULT_TEXT_EDITOR_COMPLETIONS: TextEditorCompletionItem[] = [
  { id: "frac", trigger: "\\frac", label: "\\frac", detail: "Fraction", snippet: "\\frac{${1}}{${2}}", keywords: ["fraction", "divide"] },
  { id: "dfrac", trigger: "\\dfrac", label: "\\dfrac", detail: "Display fraction", snippet: "\\dfrac{${1}}{${2}}", keywords: ["fraction"] },
  { id: "tfrac", trigger: "\\tfrac", label: "\\tfrac", detail: "Text fraction", snippet: "\\tfrac{${1}}{${2}}", keywords: ["fraction"] },
  { id: "sqrt", trigger: "\\sqrt", label: "\\sqrt", detail: "Square root", snippet: "\\sqrt{${1}}", keywords: ["root", "radical"] },
  { id: "binom", trigger: "\\binom", label: "\\binom", detail: "Binomial coefficient", snippet: "\\binom{${1}}{${2}}", keywords: ["choose", "combination"] },
  { id: "pmod", trigger: "\\pmod", label: "\\pmod", detail: "Modulo", snippet: "\\pmod{${1}}", keywords: ["mod", "modulo"] },
  { id: "text", trigger: "\\text", label: "\\text", detail: "Text in math", snippet: "\\text{${1}}", keywords: ["words", "plain"] },
  { id: "alpha", trigger: "\\alpha", label: "\\alpha", detail: "Greek alpha", snippet: "\\alpha" },
  { id: "beta", trigger: "\\beta", label: "\\beta", detail: "Greek beta", snippet: "\\beta" },
  { id: "gamma", trigger: "\\gamma", label: "\\gamma", detail: "Greek gamma", snippet: "\\gamma" },
  { id: "delta", trigger: "\\delta", label: "\\delta", detail: "Greek delta", snippet: "\\delta" },
  { id: "theta", trigger: "\\theta", label: "\\theta", detail: "Greek theta", snippet: "\\theta" },
  { id: "lambda", trigger: "\\lambda", label: "\\lambda", detail: "Greek lambda", snippet: "\\lambda" },
  { id: "pi", trigger: "\\pi", label: "\\pi", detail: "Pi", snippet: "\\pi" },
  { id: "sigma", trigger: "\\sigma", label: "\\sigma", detail: "Greek sigma", snippet: "\\sigma" },
  { id: "infty", trigger: "\\infty", label: "\\infty", detail: "Infinity", snippet: "\\infty" },
  { id: "partial", trigger: "\\partial", label: "\\partial", detail: "Partial derivative", snippet: "\\partial" },
  { id: "nabla", trigger: "\\nabla", label: "\\nabla", detail: "Nabla", snippet: "\\nabla" },
  { id: "leq", trigger: "\\leq", label: "\\leq", detail: "Less than or equal", snippet: "\\leq" },
  { id: "geq", trigger: "\\geq", label: "\\geq", detail: "Greater than or equal", snippet: "\\geq" },
  { id: "neq", trigger: "\\neq", label: "\\neq", detail: "Not equal", snippet: "\\neq" },
  { id: "approx", trigger: "\\approx", label: "\\approx", detail: "Approximately equal", snippet: "\\approx" },
  { id: "cong", trigger: "\\cong", label: "\\cong", detail: "Congruent", snippet: "\\cong" },
  { id: "equiv", trigger: "\\equiv", label: "\\equiv", detail: "Equivalent", snippet: "\\equiv" },
  { id: "sim", trigger: "\\sim", label: "\\sim", detail: "Similar", snippet: "\\sim" },
  { id: "propto", trigger: "\\propto", label: "\\propto", detail: "Proportional to", snippet: "\\propto" },
  { id: "times", trigger: "\\times", label: "\\times", detail: "Times", snippet: "\\times" },
  { id: "cdot", trigger: "\\cdot", label: "\\cdot", detail: "Centered dot", snippet: "\\cdot" },
  { id: "pm", trigger: "\\pm", label: "\\pm", detail: "Plus minus", snippet: "\\pm" },
  { id: "to", trigger: "\\to", label: "\\to", detail: "Arrow", snippet: "\\to" },
  { id: "mapsto", trigger: "\\mapsto", label: "\\mapsto", detail: "Maps to", snippet: "\\mapsto" },
  { id: "in", trigger: "\\in", label: "\\in", detail: "Element of", snippet: "\\in" },
  { id: "notin", trigger: "\\notin", label: "\\notin", detail: "Not element of", snippet: "\\notin" },
  { id: "subset", trigger: "\\subset", label: "\\subset", detail: "Subset", snippet: "\\subset" },
  { id: "subseteq", trigger: "\\subseteq", label: "\\subseteq", detail: "Subset or equal", snippet: "\\subseteq" },
  { id: "supset", trigger: "\\supset", label: "\\supset", detail: "Superset", snippet: "\\supset" },
  { id: "cup", trigger: "\\cup", label: "\\cup", detail: "Union", snippet: "\\cup" },
  { id: "cap", trigger: "\\cap", label: "\\cap", detail: "Intersection", snippet: "\\cap" },
  { id: "forall", trigger: "\\forall", label: "\\forall", detail: "For all", snippet: "\\forall" },
  { id: "exists", trigger: "\\exists", label: "\\exists", detail: "Exists", snippet: "\\exists" },
  { id: "mathbb-r", trigger: "\\mathbb{R}", label: "\\mathbb{R}", detail: "Real numbers", snippet: "\\mathbb{R}", keywords: ["reals"] },
  { id: "mathbb-z", trigger: "\\mathbb{Z}", label: "\\mathbb{Z}", detail: "Integers", snippet: "\\mathbb{Z}", keywords: ["integers"] },
  { id: "mathbb-q", trigger: "\\mathbb{Q}", label: "\\mathbb{Q}", detail: "Rational numbers", snippet: "\\mathbb{Q}", keywords: ["rationals"] },
  { id: "mathbb-n", trigger: "\\mathbb{N}", label: "\\mathbb{N}", detail: "Natural numbers", snippet: "\\mathbb{N}", keywords: ["naturals"] },
  { id: "sin", trigger: "\\sin", label: "\\sin", detail: "Sine", snippet: "\\sin" },
  { id: "cos", trigger: "\\cos", label: "\\cos", detail: "Cosine", snippet: "\\cos" },
  { id: "tan", trigger: "\\tan", label: "\\tan", detail: "Tangent", snippet: "\\tan" },
  { id: "log", trigger: "\\log", label: "\\log", detail: "Logarithm", snippet: "\\log" },
  { id: "ln", trigger: "\\ln", label: "\\ln", detail: "Natural logarithm", snippet: "\\ln" },
  { id: "hat", trigger: "\\hat", label: "\\hat", detail: "Hat accent", snippet: "\\hat{${1}}" },
  { id: "vec", trigger: "\\vec", label: "\\vec", detail: "Vector accent", snippet: "\\vec{${1}}" },
  { id: "overline", trigger: "\\overline", label: "\\overline", detail: "Overline", snippet: "\\overline{${1}}" },
  { id: "cases", trigger: "\\begin{cases}", label: "cases", detail: "Cases environment", snippet: "\\begin{cases}\n${1}\n\\end{cases}", keywords: ["piecewise"] },
  { id: "aligned", trigger: "\\begin{aligned}", label: "aligned", detail: "Aligned equations", snippet: "\\begin{aligned}\n${1}\n\\end{aligned}", keywords: ["align"] },
  { id: "pmatrix", trigger: "\\begin{pmatrix}", label: "pmatrix", detail: "Parenthesized matrix", snippet: "\\begin{pmatrix}\n${1}\n\\end{pmatrix}", keywords: ["matrix"] },
  { id: "bmatrix", trigger: "\\begin{bmatrix}", label: "bmatrix", detail: "Bracket matrix", snippet: "\\begin{bmatrix}\n${1}\n\\end{bmatrix}", keywords: ["matrix"] },
];
